[package]
name = "amplify"
version = "0.1.0"
edition = "2021"

[dependencies]
afire = { git = "https://github.com/Basicprogrammer10/afire.git", branch = "dev", features = ["extensions", "tracing"] }
rusqlite = { version = "0.27.0", features = ["bundled"] }
simple_config_parser = "1.0.0"
